Repository MicrosoftDocs/azure-docs.zh-tw, pull requests merged in 2018-10, with the labels that each got.

#113 signalr-quickstart-azure-functions-csharp.md
  articles/azure-signalr/signalr-quickstart-azure-functions-csharp.md
Labels: Accepted, Linguistic Suggestion

#119 探查 => 檢測
  articles/load-balancer/load-balancer-overview.md
Labels: Accepted, Linguistic Suggestion

#118 情節 means 場景
  articles/load-balancer/load-balancer-overview.md
Labels: Accepted, Linguistic Suggestion

#117 Lost a word
  articles/storage/common/storage-disaster-recovery-guidance.md
Labels: In Progress, Linguistic Suggestion

#122 Update index.yml
  articles/terraform/index.yml
Labels: Accepted, Linguistic Suggestion

#125 Update tutorial-csharp-module.md
  articles/iot-edge/tutorial-csharp-module.md
Labels: Accepted, Source Issue
