Repository MicrosoftDocs/azure-docs.zh-tw, pull requests merged in 2019-06, with the labels that each got.

#388 Fix mistranslation
  articles/data-factory/v1/data-factory-pig-activity.md
Labels: Accepted

#385 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-postgresql-connector.md
Labels: Accepted

#386 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-sybase-connector.md
Labels: Accepted

#387 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-teradata-connector.md
Labels: Accepted

#383 Update concept-detecting-domain-content.md
  articles/cognitive-services/Computer-vision/concept-detecting-domain-content.md
Labels: Accepted, Linguistic Suggestion

#391 Fix mistranslation
  articles/data-factory/v1/data-factory-salesforce-connector.md
Labels: Accepted, Linguistic Suggestion

#392 Fix mistranslation
  articles/data-factory/v1/data-factory-sftp-connector.md
Labels: Accepted, Linguistic Suggestion

#389 Update HowToCallVisionAPI.md
  articles/cognitive-services/Computer-vision/Vision-API-How-to-Topics/HowToCallVisionAPI.md
Labels: Accepted, Linguistic Suggestion

#393 Fix mistranslation
  articles/active-directory/develop/active-directory-claims-mapping.md
Labels: Accepted, Linguistic Suggestion

#396 Fix mistranslation
  articles/data-factory/v1/data-factory-stored-proc-activity.md
Labels: Accepted, Linguistic Suggestion

#395 Fix mistranslation
  articles/data-factory/v1/data-factory-sqlserver-connector.md
Labels: Accepted, Linguistic Suggestion

#394 Fix mistranslation
  articles/data-factory/v1/data-factory-spark.md
Labels: Accepted, Linguistic Suggestion

#401 Fix mistranslation
  articles/event-grid/event-schema-container-registry.md
Labels: Accepted, Linguistic Suggestion

#400 Fix mistranslation
  articles/event-grid/event-schema-blob-storage.md
Labels: Accepted, Linguistic Suggestion

#399 Fix mistranslation
  articles/event-grid/event-schema-azure-maps.md
Labels: Accepted, Linguistic Suggestion

#398 Fix mistranslation
  articles/digital-twins/how-to-egress-endpoints.md
Labels: Accepted, Linguistic Suggestion

#405 Fix mistranslation
  articles/event-grid/event-schema-service-bus.md
Labels: In Progress

#404 Fix mistranslation
  articles/event-grid/event-schema-resource-groups.md
Labels: In Progress

#403 Fix mistranslation
  articles/event-grid/event-schema-iot-hub.md
Labels: In Progress

#402 Fix mistranslation
  articles/event-grid/event-schema-event-hubs.md
Labels: In Progress

#409 Fix mistranslation
  articles/hdinsight/hdinsight-for-vscode.md
Labels: In Progress

#408 Fix mistranslation
  articles/event-grid/subscription-creation-schema.md
Labels: In Progress

#407 Fix mistranslation
  articles/event-grid/event-schema.md
Labels: In Progress

#406 Fix mistranslation
  articles/event-grid/event-schema-subscriptions.md
Labels: In Progress

#282 Update storage-use-azcopy.md
  articles/storage/common/storage-use-azcopy.md
Labels: In Progress, Linguistic Suggestion, Source Issue

#410 Fix mistranslation
  articles/logic-apps/logic-apps-custom-api-authentication.md
Labels: In Progress

#411 Fix mistranslation
  articles/logic-apps/logic-apps-exception-handling.md
Labels: In Progress

#412 Fix mistranslation
  articles/logic-apps/logic-apps-handle-large-messages.md
Labels: In Progress

#413 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-as2-tracking-schemas.md
Labels: In Progress

#414 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-custom-tracking-schema.md
Labels: In Progress

#417 Fix mistranslation
  articles/logic-apps/logic-apps-track-integration-account-x12-tracking-schema.md
Labels: In Progress

#418 Fix mistranslation
  articles/managed-applications/create-uidefinition-elements.md
Labels: In Progress

#419 Fix mistranslation
  articles/media-services/previous/media-services-motion-detection.md
Labels: In Progress

#422 Fix mistranslation
  articles/virtual-machine-scale-sets/virtual-machine-scale-sets-health-extension.md
Labels: In Progress

#421 Fix mistranslation
  articles/service-fabric/service-fabric-sfctl-application.md
Labels: In Progress

#420 Update
  articles/active-directory-b2c/active-directory-b2c-get-started-custom.md
Labels: Accepted, Linguistic Suggestion

#415 Update cognitive-services-containers-configuration-shared-settings-ta…
  includes/cognitive-services-containers-configuration-shared-settings-table.md
Labels: Accepted, Linguistic Suggestion

#425 Fix mistranslation
  articles/virtual-machines/extensions/azure-disk-enc-linux.md
Labels: In Progress

#424 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-windows.md
Labels: In Progress

#423 Fix mistranslation
  articles/virtual-machines/extensions/agent-dependency-linux.md
Labels: In Progress

#429 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linuxOstc.md
Labels: Accepted

#432 Fix mistranslation
  articles/virtual-machines/extensions/dsc-template.md
Labels: Accepted, Linguistic Suggestion

#433 Fix mistranslation
  articles/virtual-machines/extensions/dsc-windows.md
Labels: Accepted, Linguistic Suggestion

#430 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-windows.md
Labels: Accepted, Linguistic Suggestion

#434 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-linux.md
Labels: Accepted, Linguistic Suggestion

#431 Update cognitive-services-speech-service-rest-auth.md
  includes/cognitive-services-speech-service-rest-auth.md
Labels: Accepted, Linguistic Suggestion

#435 Fix mistranslation
  articles/virtual-machines/extensions/hpccompute-gpu-windows.md
Labels: In Progress

#437 Fix mistranslation
  articles/cognitive-services/Speech/API-Reference-REST/BingVoiceOutput.md
Labels: In Progress

#436 Fix mistranslation
  articles/virtual-machines/extensions/oms-windows.md
Labels: In Progress

#441 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-array.md
Labels: In Progress

#440 Fix mistranslation
  articles/analysis-services/analysis-services-async-refresh.md
Labels: In Progress

#438 Fix mistranslation
  articles/data-factory/v1/data-factory-amazon-simple-storage-service-connector.md
Labels: In Progress

#439 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-blob-connector.md
Labels: In Progress

#446 Fix mistranslation
  articles/governance/blueprints/reference/blueprint-functions.md
Labels: In Progress

#444 Fix mistranslation
  articles/data-factory/concepts-pipelines-activities.md
Labels: In Progress

#445 Fix mistranslation
  articles/data-factory/control-flow-if-condition-activity.md
Labels: In Progress

#448 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-actions-triggers.md
Labels: Accepted

#449 Fix mistranslation
  articles/logic-apps/logic-apps-workflow-definition-language.md
Labels: Accepted, Linguistic Suggestion

#447 Update language-support.md
  articles/cognitive-services/Speech-Service/language-support.md
Labels: Accepted

#450 Fix mistranslation
  articles/logic-apps/workflow-definition-language-functions-reference.md
Labels: Accepted

#451 Fix mistranslation
  articles/media-services/latest/media-services-event-schemas.md
Labels: Accepted, Linguistic Suggestion

#443 Fix mistranslation
  articles/azure-resource-manager/resource-group-template-functions-deployment.md
Labels: Accepted, Linguistic Suggestion

#427 Fix mistranslation
  articles/virtual-machines/extensions/chef.md
Labels: Accepted, Linguistic Suggestion

#428 Fix mistranslation
  articles/virtual-machines/extensions/custom-script-linux.md
Labels: Accepted, Linguistic Suggestion

#452 Fix mistranslation
  articles/active-directory/conditional-access/technical-reference.md
Labels: Accepted

#453 Fix mistranslation
  articles/automation/automation-graphical-authoring-intro.md
Labels: Accepted, Linguistic Suggestion

#456 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-searches-alerts.md
Labels: Accepted

#455 Fix mistranslation
  articles/azure-cache-for-redis/cache-howto-manage-redis-cache-powershell.md
Labels: Accepted, Linguistic Suggestion

#457 Fix mistranslation
  articles/azure-monitor/insights/solutions-solution-file.md
Labels: Accepted, Linguistic Suggestion

#454 Update how-to-custom-speech-human-labeled-transcriptions.md
  articles/cognitive-services/Speech-Service/how-to-custom-speech-human-labeled-transcriptions.md
Labels: Accepted

#459 Fix mistranslation
  articles/azure-monitor/log-query/unify-app-resource-data.md
Labels: Accepted

#460 Fix mistranslation
  articles/azure-monitor/platform/activity-log-export.md
Labels: Accepted

#461 Fix mistranslation
  articles/azure-monitor/platform/alerts-webhooks.md
Labels: Accepted

#462 Fix mistranslation
  articles/azure-monitor/platform/autoscale-understanding-settings.md
Labels: Accepted

#458 Update stream-analytics-javascript-user-defined-functions.md
  articles/stream-analytics/stream-analytics-javascript-user-defined-functions.md
Labels: In Progress
