Repository MicrosoftDocs/azure-docs.zh-tw, pull requests merged in 2019-01, with the labels that each got.

#150 Translation translation omission
  articles/data-factory/concepts-pipeline-execution-triggers.md
Labels: Accepted, Linguistic Suggestion

#149 Translation translation omission
  articles/azure-functions/functions-host-json.md
Labels: Accepted, Linguistic Suggestion

#148 Translation translation omission
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, Linguistic Suggestion

#147 Translation translation omission
  articles/azure-functions/functions-bindings-cosmosdb.md
Labels: Accepted, Linguistic Suggestion

#146 Translation translation omission
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, Technical Issue

#145 Translation translation omission
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Technical Issue

#156 Fix mistake
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, Technical Issue

#155 Fix mistake
  articles/azure-functions/functions-bindings-cosmosdb.md
Labels: Accepted, Technical Issue

#152 Translation translation omission
  articles/data-factory/concepts-datasets-linked-services.md
Labels: Accepted, Technical Issue

#153 Translation translation omission
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, Technical Issue

#158 Translation translation omission
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted, Technical Issue

#159 Translation translation omission
  articles/data-factory/connector-azure-cosmos-db.md
Labels: Accepted, Technical Issue

#160 Translation translation omission
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted, Technical Issue

#161 Translation translation omission
  articles/data-factory/connector-azure-search.md
Labels: Accepted, Technical Issue

#162 Translation translation omission
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, Technical Issue

#163 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-copy-data-tool.md
Labels: Accepted, Technical Issue

#164 Translation translation omission
  articles/data-factory/quickstart-create-data-factory-portal.md
Labels: Accepted, Technical Issue

#171 Translation translation omission
  articles/media-services/previous/media-services-overview.md
Labels: Accepted, Technical Issue

#170 Translation translation omission
  articles/media-services/previous/media-services-media-encoder-standard-formats.md
Labels: Accepted, Technical Issue

#169 Translation translation omission
  articles/data-factory/introduction.md
Labels: Accepted, Technical Issue

#168 Translation translation omission
  articles/data-factory/control-flow-expression-language-functions.md
Labels: Accepted, Technical Issue

#167 Translation translation omission
  articles/data-factory/copy-activity-overview.md
Labels: Accepted, Technical Issue

#166 Translation translation omission
  articles/data-factory/copy-activity-performance.md
Labels: Accepted, Technical Issue

#165 Translation translation omission
  articles/data-factory/copy-activity-fault-tolerance.md
Labels: Accepted, Technical Issue

#176 Translation translation omission
  articles/data-factory/v1/data-factory-web-table-connector.md
Labels: Accepted, Technical Issue

#175 Translation translation omission
  articles/data-factory/v1/data-factory-usql-activity.md
Labels: Accepted, Technical Issue

#174 Translation translation omission
  articles/data-factory/v1/data-factory-use-custom-activities.md
Labels: Accepted, Technical Issue

#173 Translation translation omission
  articles/data-factory/v1/data-factory-sap-hana-connector.md
Labels: Accepted, Technical Issue

#193 Translation translation omission
  articles/data-factory/transform-data-using-spark.md
Labels: Accepted, Technical Issue

#190 Translation translation omission
  articles/data-factory/transform-data-using-hadoop-pig.md
Labels: Accepted, Technical Issue

#204 Translation translation omission
  articles/data-factory/connector-mongodb-legacy.md
Labels: Accepted, Technical Issue

#202 Translation translation omission
  articles/data-factory/connector-hdfs.md
Labels: Accepted, Technical Issue

#201 Translation translation omission
  articles/data-factory/connector-ftp.md
Labels: Accepted, Technical Issue

#200 Translation translation omission
  articles/data-factory/connector-file-system.md
Labels: Accepted, Technical Issue

#199 Translation translation omission
  articles/data-factory/connector-db2.md
Labels: Accepted, Technical Issue

#198 Translation translation omission
  articles/data-factory/connector-cassandra.md
Labels: Accepted, Technical Issue

#197 Translation translation omission
  articles/data-factory/connector-azure-table-storage.md
Labels: Accepted, Technical Issue

#203 Translation translation omission
  articles/data-factory/connector-http.md
Labels: Accepted, Technical Issue

#196 Translation translation omission
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted, Technical Issue

#214 Translation translation omission
  articles/data-factory/connector-sql-server.md
Labels: Accepted, Technical Issue

#213 Translation translation omission
  articles/data-factory/connector-sftp.md
Labels: Accepted, Technical Issue

#212 Translation translation omission
  articles/data-factory/connector-sap-hana.md
Labels: Accepted, Technical Issue

#210 Translation translation omission
  articles/data-factory/connector-salesforce.md
Labels: Accepted, Technical Issue

#208 Translation translation omission
  articles/data-factory/connector-oracle.md
Labels: Accepted, Technical Issue

#207 Translation translation omission
  articles/data-factory/connector-odbc.md
Labels: Accepted, Technical Issue

#206 Translation translation omission
  articles/data-factory/connector-odata.md
Labels: Accepted, Technical Issue

#216 Fix typo
  articles/active-directory-b2c/active-directory-b2c-custom-rest-api-netfw.md
Labels: Accepted, Technical Issue

#229 Too much translation
  articles/azure-functions/functions-reference-node.md
Labels: Accepted, Linguistic Suggestion

#224 Fix typo
  articles/app-service/containers/tutorial-auth-aad.md
Labels: Accepted, Linguistic Suggestion

#223 Fix typo
  articles/app-service/app-service-web-tutorial-php-mysql.md
Labels: Accepted, Linguistic Suggestion

#222 Fix typo
  articles/app-service/app-service-web-tutorial-auth-aad.md
Labels: Accepted, Linguistic Suggestion

#219 Fix typo
  articles/active-directory/hybrid/how-to-connect-pta-upgrade-preview-authentication-agents.md
Labels: Accepted, Linguistic Suggestion

#218 Fix typo
  articles/active-directory/develop/v2-permissions-and-consent.md
Labels: Accepted, Linguistic Suggestion

#217 Fix typo
  articles/active-directory/authentication/howto-mfa-userstates.md
Labels: Accepted, Linguistic Suggestion

#228 Too much translation
  articles/azure-functions/functions-bindings-microsoft-graph.md
Labels: Accepted, Linguistic Suggestion

#227 Fix typo
  articles/automation/automation-runbook-input-parameters.md
Labels: Accepted, Linguistic Suggestion

#246 Fix missing
  articles/cognitive-services/Custom-Speech-Service/CustomSpeech-How-to-Topics/cognitive-services-custom-speech-subscribe.md
Labels: In Progress, Linguistic Suggestion

#244 Fix missing
  articles/cognitive-services/Custom-Vision-Service/csharp-tutorial-od.md
Labels: In Progress, Linguistic Suggestion

#140 Update csharp-tutorial.md
  articles/cognitive-services/Custom-Vision-Service/csharp-tutorial.md
Labels: Accepted, Linguistic Suggestion

#231 Fix missing
  articles/azure-functions/functions-twitter-email.md
Labels: Accepted, Linguistic Suggestion

#232 Fix missing
  articles/azure-maps/consumption-model.md
Labels: Accepted, Linguistic Suggestion

#236 Fix missing
  articles/azure-monitor/log-query/examples.md
Labels: Accepted, Linguistic Suggestion

#250 Fix missing
  articles/logic-apps/logic-apps-create-variables-store-values.md
Labels: Accepted, Linguistic Suggestion
