Repository MicrosoftDocs/azure-docs.zh-tw, pull requests merged in 2019-05, with the labels that each got.

#301 Fix mistranslation
  articles/data-factory/connector-amazon-redshift.md
Labels: Accepted, In Progress

#304 Fix mistranslation
  articles/data-factory/connector-azure-cosmos-db-mongodb-api.md
Labels: Accepted, In Progress

#302 Fix mistranslation
  articles/data-factory/connector-amazon-simple-storage-service.md
Labels: Accepted, In Progress

#303 Fix mistranslation
  articles/data-factory/connector-azure-blob-storage.md
Labels: Accepted, In Progress

#305 Fix mistranslation
  articles/data-factory/connector-azure-data-explorer.md
Labels: Accepted, In Progress

#306 Fix mistranslation
  articles/data-factory/connector-azure-data-lake-store.md
Labels: Accepted, In Progress

#307 Fix mistranslation
  articles/data-factory/connector-azure-file-storage.md
Labels: Accepted, In Progress

#308 Fix mistranslation
  articles/data-factory/connector-cassandra.md
Labels: Accepted, In Progress

#309 Fix mistranslation
  articles/data-factory/connector-db2.md
Labels: Accepted, In Progress

#310 Fix mistranslation
  articles/data-factory/connector-dynamics-crm-office-365.md
Labels: Accepted, In Progress

#311 Fix mistranslation
  articles/data-factory/connector-file-system.md
Labels: Accepted, In Progress

#312 Fix mistranslation
  articles/data-factory/connector-ftp.md
Labels: Accepted, In Progress

#313 Fix mistranslation
  articles/data-factory/connector-google-adwords.md
Labels: Accepted, In Progress

#314 Fix mistranslation
  articles/data-factory/connector-google-bigquery.md
Labels: Accepted, In Progress

#316 Fix mistranslation
  articles/data-factory/connector-hbase.md
Labels: Accepted, In Progress

#318 Fix mistranslation
  articles/data-factory/connector-hive.md
Labels: Accepted, In Progress

#319 Fix mistranslation
  articles/data-factory/connector-http.md
Labels: Accepted, In Progress

#330 Fix mistranslation
  articles/data-factory/connector-mongodb-legacy.md
Labels: Accepted, In Progress

#321 Fix mistranslation
  articles/data-factory/connector-jira.md
Labels: Accepted, In Progress

#323 Update sql-api-query-reference.md
  articles/cosmos-db/sql-api-query-reference.md
Labels: In Progress

#324 Update how-to-sql-query.md
  articles/cosmos-db/how-to-sql-query.md
Labels: In Progress

#332 Fix mistranslation
  articles/data-factory/connector-mongodb.md
Labels: Accepted, In Progress

#333 Fix mistranslation
  articles/data-factory/connector-odbc.md
Labels: Accepted, In Progress

#334 Fix mistranslation
  articles/data-factory/connector-office-365.md
Labels: Accepted, In Progress

#335 Fix mistranslation
  articles/data-factory/connector-oracle.md
Labels: Accepted, In Progress

#336 Fix mistranslation
  articles/data-factory/connector-phoenix.md
Labels: Accepted, In Progress

#338 Fix mistranslation
  articles/data-factory/connector-presto.md
Labels: Accepted, In Progress

#339 Fix mistranslation
  articles/data-factory/connector-rest.md
Labels: Accepted, In Progress

#340 Fix mistranslation
  articles/data-factory/connector-salesforce.md
Labels: Accepted, In Progress

#341 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse-open-hub.md
Labels: Accepted, In Progress

#342 Fix mistranslation
  articles/data-factory/connector-sap-business-warehouse.md
Labels: Accepted, In Progress

#345 Fix mistranslation
  articles/data-factory/connector-sftp.md
Labels: Accepted, In Progress

#343 Fix mistranslation
  articles/data-factory/connector-sap-ecc.md
Labels: Accepted, In Progress

#344 Fix mistranslation
  articles/data-factory/connector-sap-hana.md
Labels: Accepted, In Progress

#325 Update time-to-live.md
  articles/cosmos-db/time-to-live.md
Labels: Accepted, Linguistic Suggestion

#327 Update database-transactions-optimistic-concurrency.md
  articles/cosmos-db/database-transactions-optimistic-concurrency.md
Labels: Accepted, Linguistic Suggestion

#329 Update optimize-cost-throughput.md
  articles/cosmos-db/optimize-cost-throughput.md
Labels: Linguistic Suggestion, Partially Accepted

#331 Update optimize-cost-queries.md
  articles/cosmos-db/optimize-cost-queries.md
Labels: Linguistic Suggestion, Partially Accepted

#328 Update understand-your-bill.md
  articles/cosmos-db/understand-your-bill.md
Labels: Linguistic Suggestion, Partially Accepted

#350 doc update
  articles/active-directory/develop/v1-oauth2-client-creds-grant-flow.md
Labels: In Progress

#349 Update concepts-server-logs.md
  articles/postgresql/concepts-server-logs.md
Labels: Accepted, Linguistic Suggestion

#347 Update contoso-migration-rehost-vm-sql-ag.md
  articles/migrate/contoso-migration-rehost-vm-sql-ag.md
Labels: In Progress

#352 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, In Progress

#353 Fix mistranslation
  articles/data-factory/connector-sybase.md
Labels: Accepted, In Progress

#346 remote excess underline
  articles/app-service/overview-hosting-plans.md
Labels: Accepted, Linguistic Suggestion

#355 Fix mistranslation
  articles/data-factory/copy-activity-overview.md
Labels: Accepted, Linguistic Suggestion

#354 Fix mistranslation
  articles/data-factory/connector-teradata.md
Labels: Accepted, Linguistic Suggestion

#356 Fix mistranslation
  articles/data-factory/copy-activity-schema-and-type-mapping.md
Labels: Accepted, Linguistic Suggestion

#358 Fix mistranslation
  articles/data-factory/monitor-using-azure-monitor.md
Labels: Accepted, Linguistic Suggestion

#357 Fix mistranslation
  articles/data-factory/how-to-create-tumbling-window-trigger.md
Labels: Accepted, Linguistic Suggestion

#360 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-powershell.md
Labels: Accepted, Linguistic Suggestion

#359 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-editor.md
Labels: Accepted, Linguistic Suggestion

#362 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-azure-portal.md
Labels: Accepted, In Progress

#364 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-rest-api.md
Labels: Accepted, In Progress

#367 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-visual-studio.md
Labels: Accepted, In Progress

#368 Fix mistranslation
  articles/data-factory/v1/data-factory-create-datasets.md
Labels: Accepted, In Progress

#363 Fix mistranslation
  articles/data-factory/v1/data-factory-copy-activity-tutorial-using-powershell.md
Labels: Accepted, In Progress

#361 Fix mistranslation
  articles/data-factory/v1/data-factory-build-your-first-pipeline-using-rest-api.md
Labels: Accepted, In Progress

#365 Update howto-troubleshoot-common-connection-issues.md
  articles/postgresql/howto-troubleshoot-common-connection-issues.md
Labels: In Progress

#370 Update concepts-hyperscale-extensions.md
  articles/postgresql/concepts-hyperscale-extensions.md
Labels: Accepted, Linguistic Suggestion

#373 Fix mistranslation
  articles/data-factory/v1/data-factory-hdfs-connector.md
Labels: Accepted, Linguistic Suggestion

#372 Fix mistranslation
  articles/data-factory/v1/data-factory-ftp-connector.md
Labels: Accepted, Linguistic Suggestion

#371 Fix mistranslation
  articles/data-factory/v1/data-factory-create-pipelines.md
Labels: Accepted, Linguistic Suggestion

#375 Fix mistranslation
  articles/data-factory/v1/data-factory-http-connector.md
Labels: Accepted, Linguistic Suggestion

#374 Fix mistranslation
  articles/data-factory/v1/data-factory-hive-activity.md
Labels: Accepted, Linguistic Suggestion

#376 Fix mistranslation
  articles/data-factory/v1/data-factory-json-scripting-reference.md
Labels: Accepted, Linguistic Suggestion

#378 Fix typo
  articles/data-factory/v1/data-factory-odbc-connector.md
Labels: Accepted, In Progress

#377 Fix mistranslation
  articles/data-factory/v1/data-factory-map-reduce.md
Labels: Accepted, Linguistic Suggestion

#381 Fix mistranslation
  articles/data-factory/v1/data-factory-on-premises-mongodb-connector.md
Labels: Accepted, In Progress

#382 Fix mistranslation
  articles/data-factory/v1/data-factory-onprem-mysql-connector.md
Labels: Accepted, In Progress
