Repository MicrosoftDocs/azure-docs.zh-tw, pull requests merged in 2019-02, with the labels that each got.

#254 Fix missing
  articles/network-watcher/network-watcher-troubleshoot-overview.md
Labels: Accepted, Linguistic Suggestion

#256 app-insights-overview.md suggestion
  articles/azure-monitor/app/app-insights-overview.md
Labels: Accepted, Linguistic Suggestion

#255 Change the wrong word
  articles/cognitive-services/LUIS/luis-concept-entity-types.md
Labels: Accepted With Changes, Linguistic Suggestion

#257 Modified sentence
  articles/cognitive-services/LUIS/luis-concept-entity-types.md
Labels: Accepted, Linguistic Suggestion

#258 modify sentence
  articles/cognitive-services/LUIS/luis-tutorial-pattern.md
Labels: Linguistic Suggestion, Partially Accepted
