Repository MicrosoftDocs/azure-docs.zh-tw, pull requests merged in 2019-04, with the labels that each got.

#264 Update some words to Traditional Chinese
  articles/cosmos-db/how-to-sql-query.md
Labels: In Progress, Linguistic Suggestion

#271 Fix mistranslation
  articles/azure-monitor/platform/api-alerts.md
Labels: Accepted, In Progress

#270 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-data-warehouse-connector.md
Labels: Accepted, In Progress

#269 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-table-connector.md
Labels: Accepted, In Progress

#268 Fix mistranslation
  articles/data-factory/connector-azure-sql-data-warehouse.md
Labels: Accepted, In Progress

#276 Fix mistranslation
  articles/data-factory/connector-azure-search.md
Labels: Accepted, In Progress, Linguistic Suggestion

#275 Fix mistranslation
  articles/azure-monitor/platform/archive-diagnostic-logs.md
Labels: Accepted, In Progress, Linguistic Suggestion

#273 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-sql-connector.md
Labels: Accepted, In Progress, Linguistic Suggestion

#274 Fix mistranslation
  articles/data-factory/connector-sql-server.md
Labels: Accepted, Linguistic Suggestion

#277 Fix mistranslation
  articles/azure-monitor/insights/wire-data.md
Labels: Accepted, In Progress, Linguistic Suggestion

#278 Fix mistranslation
  articles/azure-monitor/platform/activity-logs-overview.md
Labels: Accepted, In Progress, Linguistic Suggestion

#280 Fix mistranslation
  articles/data-factory/connector-azure-sql-database-managed-insance.md
Labels: Accepted, In Progress, Linguistic Suggestion

#281 Fix mistranslation
  articles/data-factory/connector-azure-sql-database.md
Labels: Accepted, In Progress, Linguistic Suggestion

#284 Fix mistranslation
  articles/connectors/connectors-create-api-bingsearch.md
Labels: Accepted, In Progress

#283 Fix mistranslation
  articles/azure-monitor/insights/solutions-resources-automation.md
Labels: Accepted, In Progress

#287 Fix mistranslation
  articles/azure-maps/geofence-geojson.md
Labels: Accepted, In Progress

#285 Fix mistranslation
  articles/api-management/api-management-product-templates.md
Labels: Accepted, In Progress

#291 Fix mistranslation
  articles/automation/automation-manage-send-joblogs-log-analytics.md
Labels: Accepted, In Progress

#290 Fix mistranslation
  articles/automation/automation-solution-vm-management.md
Labels: Accepted, In Progress

#289 Fix mistranslation
  articles/azure-functions/functions-host-json.md
Labels: Accepted, In Progress

#288 Fix mistranslation
  articles/azure-functions/functions-host-json-v1.md
Labels: Accepted, In Progress

#272 Fix type.
  articles/cdn/index.yml
Labels: Accepted, Linguistic Suggestion

#294 Fix mistranslation
  articles/api-management/api-management-howto-use-azure-monitor.md
Labels: Accepted, In Progress

#293 Fix mistranslation
  articles/automation/automation-dsc-diagnostics.md
Labels: Accepted, In Progress

#292 Fix mistranslation
  articles/data-factory/control-flow-filter-activity.md
Labels: Accepted, In Progress

#298 Fix mistranslation
  articles/data-factory/connector-azure-table-storage.md
Labels: Accepted, In Progress

#297 Fix mistranslation
  articles/azure-monitor/insights/vminsights-log-search.md
Labels: Accepted, In Progress

#296 Fix mistranslation
  articles/api-management/api-management-howto-properties.md
Labels: Accepted, In Progress

#295 Fix mistranslation
  articles/api-management/api-management-error-handling-policies.md
Labels: Accepted, In Progress

#300 Fix mistranslation
  articles/azure-functions/functions-bindings-cosmosdb-v2.md
Labels: Accepted, Linguistic Suggestion

#299 Fix mistranslation
  articles/data-factory/v1/data-factory-azure-search-connector.md
Labels: Accepted, Linguistic Suggestion
